/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub.order;

import entities.Product;
import entities.Product_Order;
import java.awt.Font;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import util.ImageUtils;
import util.URL_Factory;


/**
 *
 * @author Admin
 */
public class InforMealPanel extends javax.swing.JPanel {

    /**
     * Creates new form InforMealPanel
     */
    
    private final Product_Order product_Order;
    private final Locale locale = new Locale("vi", "VN");
    private final NumberFormat format = NumberFormat.getNumberInstance(locale);
    private int amount;
   
    
    public InforMealPanel(Product_Order product_Order) {
        this.product_Order = product_Order;
        amount = product_Order.getAmount();
        initComponents();
        setComponents();
        setEvent();
    }

    public Product_Order getProduct_Order() {
        return product_Order;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btRemove = new javax.swing.JButton();
        lbName = new javax.swing.JLabel();
        tfNode = new javax.swing.JTextField();
        lbPrice = new javax.swing.JLabel();
        spAmount = new javax.swing.JSpinner();
        lbSum = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(153, 153, 153)));
        setMaximumSize(new java.awt.Dimension(610, 88));
        setMinimumSize(new java.awt.Dimension(610, 88));
        setPreferredSize(new java.awt.Dimension(610, 88));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);

        btRemove.setBorderPainted(false);
        btRemove.setFocusPainted(false);

        lbName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tfNode.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        tfNode.setForeground(new java.awt.Color(153, 153, 153));
        tfNode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNode.setText("Ghi Chú");
        tfNode.setEnabled(false);

        lbPrice.setBackground(new java.awt.Color(204, 204, 204));
        lbPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrice.setText("10.000");
        lbPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "Giá :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        lbPrice.setOpaque(true);

        spAmount.setModel(new javax.swing.SpinnerNumberModel(1, 1, 100, 1));
        spAmount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbSum.setBackground(new java.awt.Color(204, 204, 204));
        lbSum.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbSum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSum.setText("10.000");
        lbSum.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0), "Tổng :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        lbSum.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNode)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbSum, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbSum, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spAmount, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1)))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRemove;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbPrice;
    private javax.swing.JLabel lbSum;
    private javax.swing.JSpinner spAmount;
    private javax.swing.JTextField tfNode;
    // End of variables declaration//GEN-END:variables
    
    public JButton getButtonRemove(){
        return btRemove;
    }
    
    public JSpinner getspAmount(){
        return spAmount;
    }
    

    private void setComponents() {
        setspAmount();
        setlbSum();
        setlbPrice();
        setIcon();
        setlbName();
    }

    private void setlbSum() {
        amount = (Integer)spAmount.getValue();
        Float sum = product_Order.getProduct().getPrice()*amount;
        lbSum.setText(format.format(sum));
        
    }

    private void setlbPrice() {
        
        lbPrice.setText(format.format(product_Order.getProduct().getPrice()));
    }

    public void setspAmount() {
        spAmount.setValue(amount);
        spAmount.setFont(new Font("Tahoma",Font.PLAIN , 26));
        JComponent editor = spAmount.getEditor();
        if (editor instanceof JSpinner.DefaultEditor) {
            JSpinner.DefaultEditor spinnerEditor = (JSpinner.DefaultEditor)editor;     
            spinnerEditor.getTextField().setHorizontalAlignment(JTextField.CENTER);
        }
        
        
    }

    private void setEvent() {
        spAmountEvent();
        tfNodeEvent();
        
        
    }

    private void spAmountEvent() {
        spAmount.addChangeListener(new ChangeListener() {
            @Override
            public void stateChanged(ChangeEvent e) {
                
                amount = (Integer)spAmount.getValue();
                setlbSum();
            }
        });
    }

    private void tfNodeEvent() {
        tfNode.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                tfNode.setEnabled(true);
                tfNode.setText("");
            } 
        });
        tfNode.addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode() == KeyEvent.VK_ENTER){
                    tfNode.setEnabled(false);
                    
                }
            } 
        });
    }

    private void setIcon() {
        btRemove.setIcon(ImageUtils.loadImage(URL_Factory.IMAGE_FOLDER_URL + "\\close2.png"));
    }

    private void setlbName() {
        lbName.setText(product_Order.getProduct().getName());
    }
    
    public int getAmount(){
        return amount;
    }
    public void setAmount(int amount){
        this.amount = (amount >= 1) ? amount :1;
    }
    
}
