/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sub.order;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;


/**
 *
 * @author PC
 */
public class InformationPanel extends javax.swing.JPanel {
    

    /**
     * Creates new form InformationPanel
     */
    
    public InformationPanel() {
        initComponents();

        initEvents();
        initFont();
    }
    
    public JTable getTableFromInformationPanel(){
        return this.tbListProductOrdered;
    }
    
    public JLabel getLabelFromInformationPanel(){
        return this.lbNameTable;
    }
    
    public JLabel getOrderStatusLabelFromInformationPanel(){
        return this.lbOrderStatusIcon;
    }
    
    public JLabel getSumLabelFromInformationPanel(){
        return this.lbSum;
    }
    
    public JButton getbtPay(){
        return btnPay;
    }
    
    private void initFont(){
        lbNameTable.setFont(new Font("Tahomo",1, 40));
        lbNameTable.setForeground(Color.BLUE);
        //lbNameTable.setPreferredSize(new Dimension(50, 30));
    }

    private void initEvents() {
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsListProductOrdered = new javax.swing.JScrollPane();
        tbListProductOrdered = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnPay = new javax.swing.JButton();
        lbNameTable = new javax.swing.JLabel();
        lbVAT = new javax.swing.JLabel();
        lbOrderStatusIcon = new javax.swing.JLabel();
        lbSum = new javax.swing.JLabel();
        tfSearchTable = new javax.swing.JTextField();
        btnAll = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(610, 700));

        tbListProductOrdered.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jsListProductOrdered.setViewportView(tbListProductOrdered);

        btnAdd.setText("Thêm");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnPay.setText("Thanh toán");
        btnPay.setEnabled(false);

        lbVAT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lbVAT.setText("VAT:10%");

        lbSum.setFont(new java.awt.Font("Dialog", 1, 30)); // NOI18N
        lbSum.setForeground(new java.awt.Color(255, 0, 0));

        tfSearchTable.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        tfSearchTable.setForeground(new java.awt.Color(204, 204, 204));
        tfSearchTable.setText("Nhập bàn cần tìm kiếm");
        tfSearchTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchTableActionPerformed(evt);
            }
        });

        btnAll.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAll.setText("All");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jsListProductOrdered, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNameTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbOrderStatusIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfSearchTable, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 99, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lbSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbVAT)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jsListProductOrdered, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbVAT)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbOrderStatusIcon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                            .addComponent(lbNameTable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbSum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfSearchTable)
                                .addComponent(btnAll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void tfSearchTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchTableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSearchTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    public static javax.swing.JButton btnAll;
    private javax.swing.JButton btnPay;
    private javax.swing.JScrollPane jsListProductOrdered;
    private javax.swing.JLabel lbNameTable;
    private javax.swing.JLabel lbOrderStatusIcon;
    private javax.swing.JLabel lbSum;
    private javax.swing.JLabel lbVAT;
    private javax.swing.JTable tbListProductOrdered;
    public static javax.swing.JTextField tfSearchTable;
    // End of variables declaration//GEN-END:variables

    public JButton getbtAdd(){
        return btnAdd;
    }
    
    
    
}
